DROP TABLE IF EXISTS EC2; 

CREATE TABLE IF NOT EXISTS EC2(ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,QUESTION TEXT NOT NULL,
OPTION_A TEXT,OPTION_B TEXT,OPTION_C TEXT,OPTION_D TEXT,OPTION_E TEXT,ANSWER TEXT);

INSERT INTO EC2(QUESTION, OPTION_A, OPTION_B,OPTION_C,OPTION_D,ANSWER)
VALUES ('What does the following command do with respect to the Amazon EC2 security groups?
ec2-create-group CreateSecurityGroup', 
'Groups the user created security groups into a new group for easy access.', 
'Creates a new security group for use with your account.',
'Creates a new group inside the security group.',
'Creates a new rule inside the security group.',
'OPTION_B');

INSERT INTO EC2(QUESTION, OPTION_A, OPTION_B,OPTION_C,OPTION_D,ANSWER)
VALUES ('A web application allows customers to upload orders to an S3 bucket. The resulting Amazon S3
events trigger a Lambda function that inserts a message to an SQS queue. A single EC2 instance
reads messages from the queue, processes them, and stores them in an DynamoDB table partitioned
by unique order ID. Next month traffic is expected to increase by a factor of 10 and a Solutions
Architect is reviewing the architecture for possible scaling problems.
Which component is MOST likely to need re-architecting to be able to scale to accommodate the new
traffic?',
'Lambda function',
'SQS queue',
'EC2 instance',
'DynamoDB table',
'OPTION_C');
