# Generated by Django 4.0.3 on 2022-03-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EC2',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('QUESTION', models.TextField()),
                ('OPTION_A', models.TextField()),
                ('OPTION_B', models.TextField()),
                ('OPTION_C', models.TextField()),
                ('OPTION_D', models.TextField()),
                ('OPTION_E', models.TextField()),
                ('ANSWER', models.TextField()),
            ],
            options={
                'db_table': 'EC2',
            },
        ),
    ]
